import { Listing } from './types';

export const listings: Listing[] = [
  {
    id: '1',
    title: 'Williamsburg 2B2B — Sunny, Fully Furnished, Near L Train',
    description:
      'Bright and airy two-bedroom in the heart of Williamsburg. Hardwood floors throughout, exposed brick, and a renovated kitchen with stainless steel appliances. Building has a rooftop deck with Manhattan skyline views. Great natural light all day. No broker fee — contact directly.',
    rentalType: 'entire',
    layout: '2B2B',
    address: '123 Bedford Ave',
    zip: '11211',
    neighborhood: 'Williamsburg',
    borough: 'Brooklyn',
    availableFrom: '2026-05-01',
    availableTo: '2026-09-30',
    flexibleDates: false,
    monthlyPrice: 3200,
    monthlyNegotiable: true,
    dailyNegotiable: false,
    utilitiesIncluded: false,
    utilitiesCost: 150,
    utilitiesUnit: 'monthly',
    depositMonthlyMode: 'convention',
    depositMonthlyConvention: 'one_plus_one',
    furnished: 'full',
    furnitureDetails: 'Queen bed, sofa, dining table, wardrobe, fully equipped kitchen with fridge & microwave',
    parking: 'none',
    pets: 'yes',
    images: [
      'https://picsum.photos/seed/l1a/800/500',
      'https://picsum.photos/seed/l1b/800/500',
      'https://picsum.photos/seed/l1c/800/500',
      'https://picsum.photos/seed/l1d/800/500',
    ],
    wechat: 'nyc_rental_alex',
    phone: '(212) 555-0101',
    postedAt: '2026-03-25T10:00:00Z',
  },
  {
    id: '2',
    title: "Hell's Kitchen 2B1B Secondary Bedroom — Short or Long Term",
    description:
      "Private secondary bedroom in a shared 2-bedroom apartment steps from Hell's Kitchen. Fully furnished room with a comfortable single bed, desk, and wardrobe. The apartment has a modern kitchen and spacious living room. Great for students, interns, or anyone settling into the city.",
    rentalType: 'room',
    roomType: 'secondary',
    layout: '2B1B',
    address: '456 W 47th St',
    zip: '10019',
    neighborhood: "Hell's Kitchen",
    borough: 'Manhattan',
    availableFrom: '2026-04-10',
    availableTo: '2026-10-31',
    flexibleDates: true,
    monthlyPrice: 1800,
    monthlyNegotiable: false,
    dailyPrice: 85,
    dailyNegotiable: true,
    utilitiesIncluded: true,
    depositMonthlyMode: 'convention',
    depositMonthlyConvention: 'one_plus_one',
    depositDailyMode: 'fixed',
    depositDailyAmount: 510,
    furnished: 'full',
    furnitureDetails: 'Single bed, desk, wardrobe, bedside lamp — shared living room furniture included',
    parking: 'none',
    pets: 'no',
    roommatesCount: 3,
    roommatesGender: 'mixed',
    sharedBathrooms: 1,
    images: [
      'https://picsum.photos/seed/l2a/800/500',
      'https://picsum.photos/seed/l2b/800/500',
      'https://picsum.photos/seed/l2c/800/500',
    ],
    wechat: 'hk_room_maria',
    phone: '(646) 555-0202',
    postedAt: '2026-03-26T14:30:00Z',
  },
  {
    id: '3',
    title: 'Astoria 1B1B — Quiet Block, Free Parking, Near N/W Train',
    description:
      'One-bedroom apartment on a quiet, tree-lined block in Astoria. Partially furnished with bed frame and some kitchen appliances. Close to the N/W trains and the best Greek food in NYC. Building has laundry in the basement. Pet-friendly — landlord open to discussion.',
    rentalType: 'entire',
    layout: '1B1B',
    address: '78 31st Ave',
    zip: '11103',
    neighborhood: 'Astoria',
    borough: 'Queens',
    availableFrom: '2026-05-01',
    availableTo: '2026-12-31',
    flexibleDates: false,
    monthlyPrice: 2600,
    monthlyNegotiable: false,
    dailyNegotiable: false,
    utilitiesIncluded: false,
    utilitiesCost: 120,
    utilitiesUnit: 'monthly',
    depositMonthlyMode: 'custom',
    depositMonthlyAmount: 2600,
    furnished: 'partial',
    furnitureDetails: 'Bed frame (no mattress), refrigerator, some kitchen appliances',
    parking: 'free',
    pets: 'negotiable',
    images: [
      'https://picsum.photos/seed/l3a/800/500',
      'https://picsum.photos/seed/l3b/800/500',
    ],
    email: 'james.park@email.com',
    postedAt: '2026-03-27T09:15:00Z',
  },
  {
    id: '4',
    title: 'Park Slope Master Bedroom — Female Roommates, Near Prospect Park',
    description:
      'Private master bedroom in a lovely 3-bedroom pre-war apartment, one block from Prospect Park. The apartment has high ceilings, original hardwood floors, and a renovated bathroom. Two friendly female roommates, very clean and quiet household. Great community vibe.',
    rentalType: 'room',
    roomType: 'master',
    layout: '3B2B',
    address: '290 8th Ave',
    zip: '11215',
    neighborhood: 'Park Slope',
    borough: 'Brooklyn',
    availableFrom: '2026-04-15',
    availableTo: '2026-10-14',
    flexibleDates: false,
    monthlyPrice: 1500,
    monthlyNegotiable: false,
    dailyNegotiable: false,
    utilitiesIncluded: true,
    depositMonthlyMode: 'convention',
    depositMonthlyConvention: 'one_plus_one',
    furnished: 'full',
    furnitureDetails: 'Queen bed, wardrobe, two nightstands, desk and chair',
    parking: 'none',
    pets: 'yes',
    roommatesCount: 3,
    roommatesGender: 'female',
    sharedBathrooms: 2,
    images: [
      'https://picsum.photos/seed/l4a/800/500',
      'https://picsum.photos/seed/l4b/800/500',
      'https://picsum.photos/seed/l4c/800/500',
    ],
    wechat: 'parkslope_rachel',
    postedAt: '2026-03-28T11:00:00Z',
  },
  {
    id: '5',
    title: 'Harlem Studio — No Deposit, Daily or Monthly, All Utilities Included',
    description:
      'Unfurnished studio in a well-maintained building in Central Harlem. All utilities included in rent — move-in ready for someone with their own furniture. Ideal for short or long-term stays. Steps from the 2/3 express train. No deposit required.',
    rentalType: 'entire',
    layout: 'Studio',
    address: '340 W 119th St',
    zip: '10027',
    neighborhood: 'Harlem',
    borough: 'Manhattan',
    availableFrom: '2026-04-01',
    availableTo: '2026-07-31',
    flexibleDates: true,
    monthlyPrice: 2200,
    monthlyNegotiable: false,
    dailyPrice: 95,
    dailyNegotiable: false,
    utilitiesIncluded: true,
    depositMonthlyMode: 'convention',
    depositMonthlyConvention: 'none',
    depositDailyMode: 'none',
    furnished: 'none',
    parking: 'none',
    pets: 'negotiable',
    images: [
      'https://picsum.photos/seed/l5a/800/500',
      'https://picsum.photos/seed/l5b/800/500',
    ],
    wechat: 'harlem_studio_d',
    phone: '(212) 555-0505',
    postedAt: '2026-03-28T16:45:00Z',
  },
  {
    id: '6',
    title: 'Bushwick Living Room Conversion — Partition + Window, $90/day',
    description:
      'Partitioned living room in a shared 2B apartment in vibrant Bushwick. Has a proper partition wall and a window — good natural light and privacy. Near the J/M/Z trains and surrounded by galleries and cafes. Great for short-term stays.',
    rentalType: 'room',
    roomType: 'living',
    layout: '2B1B',
    address: '15 Wyckoff Ave',
    zip: '11237',
    neighborhood: 'Bushwick',
    borough: 'Brooklyn',
    availableFrom: '2026-04-01',
    availableTo: '2026-06-30',
    flexibleDates: false,
    dailyPrice: 90,
    dailyNegotiable: false,
    monthlyNegotiable: false,
    utilitiesIncluded: false,
    utilitiesCost: 30,
    utilitiesUnit: 'daily',
    depositDailyMode: 'fixed',
    depositDailyAmount: 540,
    furnished: 'partial',
    furnitureDetails: 'Futon, desk, shelving unit',
    parking: 'none',
    pets: 'no',
    roommatesCount: 2,
    roommatesGender: 'mixed',
    sharedBathrooms: 1,
    hasPartition: true,
    hasWindow: true,
    images: [
      'https://picsum.photos/seed/l6a/800/500',
      'https://picsum.photos/seed/l6b/800/500',
    ],
    wechat: 'bushwick_marco',
    postedAt: '2026-03-29T12:30:00Z',
  },
  {
    id: '7',
    title: 'Jersey City 2B2B — Fully Furnished, Parking, PATH to Manhattan',
    description:
      'Spacious two-bedroom apartment in Journal Square, Jersey City. All rooms fully furnished, washer/dryer in unit, and paid parking available in the building. Easy PATH train access — 20 minutes to Midtown Manhattan. Great for those priced out of NYC.',
    rentalType: 'entire',
    layout: '2B2B',
    address: '36 Journal Square Plaza',
    zip: '07306',
    neighborhood: 'Journal Square',
    borough: 'Jersey City',
    availableFrom: '2026-05-15',
    availableTo: '2027-05-14',
    flexibleDates: false,
    monthlyPrice: 2800,
    monthlyNegotiable: false,
    dailyNegotiable: false,
    utilitiesIncluded: false,
    utilitiesCost: 160,
    utilitiesUnit: 'monthly',
    depositMonthlyMode: 'convention',
    depositMonthlyConvention: 'one_plus_one',
    furnished: 'full',
    furnitureDetails: 'Both bedrooms fully furnished with queen beds, wardrobes, desks. Living room sofa + TV. Washer/dryer in unit.',
    parking: 'paid',
    parkingFee: 100,
    pets: 'yes',
    images: [
      'https://picsum.photos/seed/l7a/800/500',
      'https://picsum.photos/seed/l7b/800/500',
      'https://picsum.photos/seed/l7c/800/500',
    ],
    wechat: 'jc_home_sophie',
    email: 's.laurent@email.com',
    postedAt: '2026-03-29T08:00:00Z',
  },
  {
    id: '8',
    title: 'Long Island City 1B1B — No Deposit, Negotiable, 7 Train Direct',
    description:
      'Brand new one-bedroom in LIC with Manhattan skyline views. IKEA furniture throughout, smart TV, and modern kitchen appliances. Building has a gym and residents lounge. One stop to Midtown via the 7 train. No security deposit required — price negotiable.',
    rentalType: 'entire',
    layout: '1B1B',
    address: '22-33 Jackson Ave',
    zip: '11101',
    neighborhood: 'Long Island City',
    borough: 'Queens',
    availableFrom: '2026-05-01',
    availableTo: '2027-04-30',
    flexibleDates: false,
    monthlyPrice: 3000,
    monthlyNegotiable: true,
    dailyNegotiable: false,
    utilitiesIncluded: false,
    utilitiesCost: 130,
    utilitiesUnit: 'monthly',
    depositMonthlyMode: 'convention',
    depositMonthlyConvention: 'none',
    furnished: 'full',
    furnitureDetails: 'IKEA furniture throughout: queen bed, wardrobe, sofa, dining set. Smart TV, kitchen appliances included.',
    parking: 'none',
    pets: 'no',
    images: [
      'https://picsum.photos/seed/l8a/800/500',
      'https://picsum.photos/seed/l8b/800/500',
      'https://picsum.photos/seed/l8c/800/500',
    ],
    email: 'e.zhou@email.com',
    phone: '(718) 555-0808',
    postedAt: '2026-03-30T09:00:00Z',
  },
];

export function getListingById(id: string): Listing | undefined {
  return listings.find((l) => l.id === id);
}
