import { Listing } from './types';

export const listings: Listing[] = [
  {
    id: '1',
    title: 'Sunny 1BR in Williamsburg — Steps from L Train',
    description:
      'Bright and airy one-bedroom in the heart of Williamsburg. Hardwood floors throughout, exposed brick, and a renovated kitchen with stainless steel appliances. Building has a rooftop deck with Manhattan skyline views. Perfect for young professionals. No broker fee.',
    price: 3200,
    availableFrom: '2026-04-15',
    borough: 'Brooklyn',
    neighborhood: 'Williamsburg',
    zipCode: '11211',
    bedrooms: 1,
    bathrooms: 1,
    sqft: 620,
    images: [
      'https://picsum.photos/seed/apt1a/800/500',
      'https://picsum.photos/seed/apt1b/800/500',
      'https://picsum.photos/seed/apt1c/800/500',
    ],
    contactName: 'Alex Chen',
    contactEmail: 'alex.chen@email.com',
    contactPhone: '(212) 555-0101',
    postedAt: '2026-03-25T10:00:00Z',
    amenities: ['Rooftop deck', 'Laundry in building', 'Dishwasher', 'Pet friendly'],
  },
  {
    id: '2',
    title: 'Spacious Studio in Hell\'s Kitchen — Furnished',
    description:
      'Fully furnished studio in a prime Midtown West location. Walking distance to Times Square and major subway lines (A/C/E, 1/2/3). The apartment features a queen bed, sofa, desk, and fully equipped kitchen. Ideal for short-term stays or those looking to settle in quickly.',
    price: 2800,
    availableFrom: '2026-04-01',
    availableTo: '2026-10-01',
    borough: 'Manhattan',
    neighborhood: "Hell's Kitchen",
    zipCode: '10019',
    bedrooms: 0,
    bathrooms: 1,
    sqft: 480,
    images: [
      'https://picsum.photos/seed/apt2a/800/500',
      'https://picsum.photos/seed/apt2b/800/500',
    ],
    contactName: 'Maria Santos',
    contactEmail: 'maria.s@email.com',
    contactPhone: '(646) 555-0202',
    postedAt: '2026-03-26T14:30:00Z',
    amenities: ['Furnished', 'Doorman', 'Gym', 'Elevator', 'Dishwasher'],
  },
  {
    id: '3',
    title: '2BR Duplex in Astoria with Private Terrace',
    description:
      'Stunning two-bedroom duplex with a private terrace in the vibrant Astoria neighborhood. Open-plan living area, modern kitchen, and two full bathrooms. Close to the N/W trains and the best Greek food in NYC. Quiet, tree-lined block.',
    price: 3800,
    availableFrom: '2026-05-01',
    borough: 'Queens',
    neighborhood: 'Astoria',
    zipCode: '11103',
    bedrooms: 2,
    bathrooms: 2,
    sqft: 950,
    images: [
      'https://picsum.photos/seed/apt3a/800/500',
      'https://picsum.photos/seed/apt3b/800/500',
      'https://picsum.photos/seed/apt3c/800/500',
    ],
    contactName: 'James Park',
    contactEmail: 'j.park@email.com',
    postedAt: '2026-03-27T09:15:00Z',
    amenities: ['Private terrace', 'Dishwasher', 'Storage unit', 'Bike storage'],
  },
  {
    id: '4',
    title: 'Cozy 1BR in Park Slope — Near Prospect Park',
    description:
      'Charming one-bedroom apartment one block from Prospect Park. Pre-war building with beautiful details: crown molding, high ceilings, original hardwood floors. Recently renovated bathroom. Quiet residential block on a beautiful tree-lined street.',
    price: 2950,
    availableFrom: '2026-04-01',
    borough: 'Brooklyn',
    neighborhood: 'Park Slope',
    zipCode: '11215',
    bedrooms: 1,
    bathrooms: 1,
    sqft: 700,
    images: [
      'https://picsum.photos/seed/apt4a/800/500',
      'https://picsum.photos/seed/apt4b/800/500',
    ],
    contactName: 'Rachel Kim',
    contactEmail: 'rachel.kim@email.com',
    contactPhone: '(718) 555-0404',
    postedAt: '2026-03-28T11:00:00Z',
    amenities: ['Hardwood floors', 'High ceilings', 'Laundry in basement', 'Cats OK'],
  },
  {
    id: '5',
    title: 'Modern 3BR in Harlem — Renovated Townhouse',
    description:
      'Beautifully renovated three-bedroom floor-through in a historic Harlem townhouse. Central A/C, chef\'s kitchen with island, and in-unit washer/dryer. Huge master bedroom with en-suite bath. Steps from the 2/3 express train. A rare find at this price.',
    price: 4500,
    availableFrom: '2026-06-01',
    borough: 'Manhattan',
    neighborhood: 'Harlem',
    zipCode: '10027',
    bedrooms: 3,
    bathrooms: 2,
    sqft: 1400,
    images: [
      'https://picsum.photos/seed/apt5a/800/500',
      'https://picsum.photos/seed/apt5b/800/500',
      'https://picsum.photos/seed/apt5c/800/500',
      'https://picsum.photos/seed/apt5d/800/500',
    ],
    contactName: 'David Wright',
    contactEmail: 'd.wright@email.com',
    contactPhone: '(212) 555-0505',
    postedAt: '2026-03-28T16:45:00Z',
    amenities: ['In-unit W/D', 'Central A/C', "Chef's kitchen", 'Private garden access'],
  },
  {
    id: '6',
    title: 'Studio with Hudson River Views — Financial District',
    description:
      'Contemporary studio on the 24th floor with sweeping Hudson River views. Floor-to-ceiling windows, open kitchen, and a sleek bathroom. Full-service building with 24/7 doorman and concierge. Walking distance to Wall Street and the Oculus.',
    price: 3100,
    availableFrom: '2026-04-15',
    borough: 'Manhattan',
    neighborhood: 'Financial District',
    zipCode: '10004',
    bedrooms: 0,
    bathrooms: 1,
    sqft: 520,
    images: [
      'https://picsum.photos/seed/apt6a/800/500',
      'https://picsum.photos/seed/apt6b/800/500',
    ],
    contactName: 'Sophie Laurent',
    contactEmail: 's.laurent@email.com',
    postedAt: '2026-03-29T08:00:00Z',
    amenities: ['Doorman', 'Concierge', 'Gym', 'Roof deck', 'Bike room', 'Elevator'],
  },
  {
    id: '7',
    title: '1BR in Bushwick — Artist-Friendly Loft Style',
    description:
      'High-ceiling loft-style one-bedroom in a converted warehouse. Polished concrete floors, exposed ducts, and huge south-facing windows. Large open living space perfect for creatives. Near the J/M/Z trains and surrounded by galleries and cafes.',
    price: 2600,
    availableFrom: '2026-04-01',
    borough: 'Brooklyn',
    neighborhood: 'Bushwick',
    zipCode: '11237',
    bedrooms: 1,
    bathrooms: 1,
    sqft: 800,
    images: [
      'https://picsum.photos/seed/apt7a/800/500',
      'https://picsum.photos/seed/apt7b/800/500',
    ],
    contactName: 'Marco Torres',
    contactEmail: 'm.torres@email.com',
    contactPhone: '(347) 555-0707',
    postedAt: '2026-03-29T12:30:00Z',
    amenities: ['High ceilings', 'Exposed brick', 'Pet friendly', 'Storage'],
  },
  {
    id: '8',
    title: '2BR in Long Island City — Manhattan Views',
    description:
      'Brand new two-bedroom apartment in LIC with stunning Manhattan skyline views. In-unit washer/dryer, dishwasher, and central A/C. Building amenities include a pool, gym, and residents lounge. One stop to Midtown via the 7 train.',
    price: 4200,
    availableFrom: '2026-05-15',
    borough: 'Queens',
    neighborhood: 'Long Island City',
    zipCode: '11101',
    bedrooms: 2,
    bathrooms: 2,
    sqft: 1050,
    images: [
      'https://picsum.photos/seed/apt8a/800/500',
      'https://picsum.photos/seed/apt8b/800/500',
      'https://picsum.photos/seed/apt8c/800/500',
    ],
    contactName: 'Emily Zhou',
    contactEmail: 'e.zhou@email.com',
    postedAt: '2026-03-30T09:00:00Z',
    amenities: ['Pool', 'Gym', 'In-unit W/D', 'Doorman', 'Roof deck', 'Central A/C'],
  },
];

export function getListingById(id: string): Listing | undefined {
  return listings.find((l) => l.id === id);
}
